### PR TITLE
Use symbols to make _vars truly private

### PR DESCRIPTION
**Pull request by wesleytodd**
Don't know if you are interested in this, but it is a nice way to clean up the api and not expose the "private" variables.

### CODE REVIEW

**Comment by wesleytodd** [comment]
Also, I can add the same stuff for the private methods, but I thought I would get your opinion before doing all the work.

**Comment by vmakhaev** [comment]
Thanks for your work on PRs.
For this one I'm not sure. Looks like code cleanness suffer a little from these constructs: `this[_field].dosmth()` compared to `this._field.dosmth()`. Does it worth it?

**Comment by wesleytodd** [comment]
That exact reason is why I am not sure everyone would be into this method.  

In my experience, if you expose it they will use it.  So for any third party library or open source project, I prefer to keep the api I expose as small as possible.  Previously javascript didn't actually have a mechanism for doing this, thus the pattern of `_var`'s.  

While it is a tax on the developers of the module, the benefit of not having to maintain support for those internal variables is worth it in the long run, IMO.  Anyway, it is totally up to you as it is your library, and I will be using it either way.  BUT, since it was easy enough to demonstrate the concept since you were already writing es2015/16, I figured I would do the PR.

Thanks for the good work on the module! :)

**Comment by vmakhaev** [comment]
I got your point. But I think it's overkill. If someone wants to use private methods, let's them do it on their own risk. I also sometimes use not documented features, but do not expect them to be supported. AFAIK, they are discussing private methods for ES6 classes. I think this will be a way to go.
BTW, I added you as collaborator, feel free to contribute.

**Comment by wesleytodd** [comment]
Sounds good. And thanks for adding me, if I find anything else while getting this integrated I will for sure keep up the contributions.

**Pull request closed without merging**
